version: "3.9"
services:
  server:
    build:  ./backend
    ports:
  - "5000:5000"
    volumes:
    - ./backend:/app
    environment:
      FLASK_ENV: development
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/user/src/app
    depends_on:
      - server
